version: '3'

services:
  broker-service:
    build:
      dockerfile: broker/broker.Dockerfile
    restart: always
    ports:
      - "8090:80"
    deploy:
      mode: replicated
      replicas: 1
  authentication-service:
    build:
      dockerfile: authentication/authentication.Dockerfile
    restart: always
    ports:
      - "8081:80"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DATABASE_URL: "host=postgres user=postgres password=password dbname=users port=5432 sslmode=disable TimeZone=UTC connect_timeout=5"
  postgres:
    image: 'postgres:14.0'
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./project/db-data/postgres/:/var/lib/postgresql/data/